command: ["streamlit", "run", "app.py"]

env:
  - name: "STREAMLIT_GATHER_USAGE_STATS"
    value: "false"

  - name: "VECTOR_SEARCH_ENDPOINT_NAME"
    value: "wb_ai_search_endpoint"

  - name: "VECTOR_SEARCH_INDEX_NAME"
    value: "worldbank_govtech.govtech.govtech_report_chunks_index"

  - name: "LLM_ENDPOINT_NAME"
    value: "databricks-meta-llama-3-3-70b-instruct"

  - name: "CATALOG"
    value: "worldbank_govtech"

  - name: "SCHEMA"
    value: "govtech"

  - name: "GTMI_TABLE"
    value: "worldbank_govtech.govtech.silver_gtmi_scores"

  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "f07a9d8496acc8b1"